### ISSUE TITLE
Roadmap Schema UI

### ISSUE THREAD

**Issue by codeliner** [prooph/event-store-mgmt-ui#1]
With  https://github.com/proophsoftware/event-machine/pull/79 and https://github.com/proophsoftware/event-machine/pull/78 @camuthig laid the foundation to consume an API description (a JSON Schema) of an Event Machine powered service. The plan is to use that description in a frontend app to generate an API documentation as well as an editor to send messages and see the results. 

The app should work in a similar way like the available GraphQL clients.

My plan is to integrate the functionality in the [event-store-mgmt-ui](https://github.com/prooph/event-store-mgmt-ui).

This allows non Event Machine based apps to provide a similar JSON Schema and make use of the same frontend.  I need to finish some other tasks first before I can start working on the editor:

## Open tasks with high prio:

- [ ] First dev version of event-store-mgmt-ui should be published first, to collect feedback early
    - [ ] Move actions from event-store-http-api to event-store-http-middleware: https://github.com/prooph/event-store-http-api/issues/34
    - [ ] Update proophessor-do to expressive 3.0 and integrate event-store-http-middleware
    - [ ] Set up event-store-mgmt-ui for proophessor-do
    - [ ] Spread the word about this awesome new tool

## Tasks related to Schema UI
- [ ] Backend services should be configurable in event-store-mgmt-ui
    - [ ]  event-store-http-api endpoint
    - [ ] message schema endpoint (optional)
    - [ ] messagebox endpoint (optional)
- [ ] Schema Editor should support two modes: a "raw" mode to send messages as simple JSON objects and a "schema connected mode" that is only available if a message schema endpoint is configured and the schema returned by that endpoint is valid
- [ ] API documentation viewer if message schema endpoint is configured

## Additional tasks
- [ ] Expand message-flow-analyzer to generate such JSON Schema when scanning a project

**Comment by prolic** [comment]
:+1: :exclamation:
